[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
age = { version = "0.9.2", features = ["async"] }
anyhow = "1.0.75"
blake3 = { version = "1.5.0", features = ["serde"] }
chrono = "0.4.31"
regex = "1.10.2"
rustls = "0.22.0"
rustls-pemfile = "2.0.0"
rustls-pki-types = "1.0.1"
serde = { version = "1.0.193", features = ["derive"] }
serde_with = "3.4.0"
thiserror = "1.0.50"
tokio = { version = "1.34.0", features = ["full", "net"] }
tokio-rustls = "0.25"
toml = "0.8.8"
tracing = "0.1.40"
tracing-appender = "0.2.3"
tracing-subscriber = "0.3.18"
