socket_address = "localhost"
socket_port = 5358
root_ca_path = "./ssl/ca.crt"
recipiant_path = "./ssl/age.crt"
certificate_path = "./ssl/backups_client.crt"
key_path = "./ssl/backups_client.key"

[[service_config]]
[service_config.DockerPostgres.config]
folder_name = "assignment_tracker_database"
docker_container = "assignment-tracker-database-1"
postgres_user = "postgres"
postgres_database = "postgres"
backup_configs = [
	{ folder_name = "hourly", backup_interval = 3600 },
	{ folder_name = "daily", backup_interval = 86400 },
	{ folder_name = "weekly", backup_interval = 604800 },
]
