[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.34", features = ["full"] }
dotenvy = "0.15"
thiserror = "1.0"
pretty_env_logger = "0.5"
log = "0.4"
anyhow = "1.0.75"
regex = "1.10.2"
tokio-rustls = "0.24.1"
