socket_address = "127.0.0.1:5358"
root_ca_path = "./ssl/ca.crt"
age_key_path = "./ssl/age.key"
certificate_path = "./ssl/backups.trentshailer.com.crt"
private_key_path = "./ssl/backups.trentshailer.com.key"
backup_path = "./backups"


[[service_config]]
folder_name = "timetable_database"
backup_configs = [
	{ folder_name = "hourly", max_files = 24 },
	{ folder_name = "daily", max_files = 30 },
	{ folder_name = "weekly", max_files = 52 },
]

[[service_config]]
folder_name = "assignment_tracker_database"
backup_configs = [
	{ folder_name = "hourly", max_files = 24 },
	{ folder_name = "daily", max_files = 30 },
	{ folder_name = "weekly", max_files = 52 },
]

[[service_config]]
folder_name = "link_storage_database"
backup_configs = [
	{ folder_name = "hourly", max_files = 24 },
	{ folder_name = "daily", max_files = 30 },
	{ folder_name = "weekly", max_files = 52 },
]
