[package]
name = "shared"
version = "0.2.0"
edition = "2021"


[dependencies]
rustls = { workspace = true }
rustls-pemfile = { workspace = true }
rustls-pki-types = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
